name: Publish docs via GitHub
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Replace GPT API key in chatbot.html
        run: |
          sed -i 's|GPT_API_KEY_HERE|${{ secrets.GPT_API_KEY }}|g' docs/chatbot.html
      - name: Deploy docs
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
