name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and publish docs
      env:
        GPT_API_KEY: ${{ secrets.GPT_API_KEY_HERE }}
      run: |
        mkdocs build
        mkdocs gh-deploy --force